server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: '${loki_endpoint}/loki/api/v1/push'

scrape_configs:

  - job_name: system
    pipeline_stages:
    - multiline:
        firstline: '^\w{3}\s+\d{1,2}\s\d{2}:\d{2}:\d{2}'
        max_wait_time: 3s
    - regex:
        expression: '^(?P<timestamp>\w{3}\s+\d{1,2}\s\d{2}:\d{2}:\d{2})\s(?P<address>[\w\-]+)\s(?P<unit>[\w\-]+)\[\d+\]:\s(?P<message>(?s:.*))$'
    - timestamp:
        source: timestamp
        format: Mar  7 17:59:06
    - labels:
        address:
        unit:
        message:
    static_configs:
    - targets:
        - localhost
      labels:
        job: system
        region: ${region}
        cloud: ${cloud}
        __path__: /var/log/*log
 
  - job_name: health
    pipeline_stages:
    - multiline:
        firstline: '^\w{3}\s+\d{1,2}\s\d{2}:\d{2}:\d{2}'
        max_wait_time: 3s
    - regex:
        expression: '^(?P<timestamp>\w{3}\s+\d{1,2}\s\d{2}:\d{2}:\d{2})\s(?P<address>[\w\-]+)\s(?P<unit>[\w\-]+)\[\d+\]:\s\[(?P<level>\w+)\]\s(?P<message>(?s:.*))$'
    - timestamp:
        source: timestamp
        format: Mar  7 17:59:06
    - labels:
        address:
        unit:
        message:
    - match:
        selector: '{level!="INFO"}'
        action: drop
    static_configs:
    - targets:
        - localhost
      labels:
        job: health
        region: ${region}
        cloud: ${cloud}
        __path__: /var/log/*log